### ISSUE TITLE
new object: brt station

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#20]

**Comment by kfarr** [comment]
example from streetmix
https://streetmix.net/kfarr/69/3dstreet-pr130-test-street
![image](https://user-images.githubusercontent.com/470477/149877755-33e57b82-4f41-46a9-959b-86d953a9b971.png)

**Comment by gnansai** [comment]
@kfarr Could you share any real-world reference images of BRT station that you would prefer?

**Comment by kfarr** [comment]
Yes here are a few images from different angles
front / top: https://www.flickr.com/photos/carlosfpardo/6891270912/
front / side: https://www.flickr.com/photos/carlosfpardo/46483732974/
front / interior (you'll have to zoom in a lot): https://www.flickr.com/photos/carlosfpardo/6891270912/

**Comment by kfarr** [comment]
alternative design

side / interior: https://www.flickr.com/photos/carlosfpardo/47143536722/
front: https://www.flickr.com/photos/carlosfpardo/47143535332/

**Comment by kfarr** [comment]
wip images:
![image](https://user-images.githubusercontent.com/470477/151103926-7528a37e-8747-4f2c-a2f9-3717810e4a43.png)

![image](https://user-images.githubusercontent.com/470477/151103935-fbe95a03-aaa2-49d5-8d5f-ab61cfd112de.png)

![image](https://user-images.githubusercontent.com/470477/151103940-00a37df0-56da-403b-9551-b293d4816bdf.png)

![image](https://user-images.githubusercontent.com/470477/151103942-7650de34-5d40-4c47-b04b-8076d7fa80cb.png)

![image](https://user-images.githubusercontent.com/470477/151103949-c96c01d3-59b8-4eeb-ab13-3fa61002a196.png)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/151648026-616a3421-a240-4371-b03f-addb31f12423.png)
I made small changes to brt-station

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/sets/brt-station/gltf-exports
I uploaded brt-station model here

**Comment by kfarr** [comment]
This asset build portion of this task is complete and is now awaiting implementation in 3dstreet viewer

**Comment by Algorush** [comment]
![brt-station](https://user-images.githubusercontent.com/32197767/231562452-77468a67-2ab2-467e-9937-9ffb66cfa47c.jpg)
the dimensions of brt-station are slightly larger than the width of the brt-station segment from streetmix. Steps/ladders cross the train model.
![brt](https://user-images.githubusercontent.com/32197767/231592280-6be7ecd7-c4cb-452e-8a27-5161884750a8.jpg)
I made the scale of the brt station itself 0.93. Now it looks good:
![brt](https://user-images.githubusercontent.com/32197767/231597393-f98f6948-97c2-4e0b-a820-ab4571078e1f.jpg)

**Comment by kfarr** [comment]
The BRT station in streetmix will scale to any size, for exampe:
![image](https://user-images.githubusercontent.com/470477/233224882-943ef4f2-c2c6-4ffb-83d9-7cab7576ab79.png)

However, the default size is ~13.3 feet wide:
![image](https://user-images.githubusercontent.com/470477/233224896-d2d8b2ec-7c75-4cf6-8e28-c6ed6a13b9b8.png)

So I would suggest our model fit the 13.3 feet default.

**Comment by kfarr** [comment]
done! https://github.com/3DStreet/3dstreet/pull/268
