### ISSUE TITLE
new building type: arcade style buildings

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#21]
Picture examples from streetmix
![image](https://user-images.githubusercontent.com/470477/148131780-862e5d90-0cca-4358-815b-bb5c2a5b8252.png)

![image](https://user-images.githubusercontent.com/470477/148131805-0c142c14-cb0f-49b1-a07a-02222526f697.png)

**Comment by gnansai** [comment]
@kfarr If you have any real world reference images, please share. They would be useful.
Thank you

**Comment by kfarr** [comment]
Here are some examples of arcade construction style or similar:
https://en.wikipedia.org/wiki/File:Metz_-_Place_Saint-Louis_-622.jpg
Lego style (helpful to see some key elements for low poly) https://www.aliexpress.com/item/1005002870580500.html
https://www.alamy.com/arcades-in-the-elegant-buildings-of-the-center-of-milan-italy-image181198422.html
https://www.momentousasia.com/arcade-buildings-in-guangdong/ (various pictures in the gallery on the page)

**Comment by gnansai** [comment]
https://user-images.githubusercontent.com/25223402/151479579-15319280-8173-4e82-a200-f6e3e4e84a43.mp4

I made a modular asset in Blender using geometry nodes

**Comment by kfarr** [comment]
This is great @gnansai . I assume this also uses the common atlases? It would be good to save this original blender file with the geometry nodes in the 3dstreet-assets repo?

For now we will need an old-fashioned gltf export. Using this fantastic tool you've created, can you export 4 different arched building variants combined into 1 gltf with 1 material?
Length: between 2-7 -- randomized or as you choose 
Width: 4 for all buildings
Height: between 1-4 -- randomized or as you choose

Roof geometry: you choose

Is it possible to vary the main building color for 2 of them? The other 2 should use the colors that you have already chosen as default.

**Comment by gnansai** [comment]
@kfarr, It is using same material atlas. I will upload the blender file in in GitHub. 
 yes, we customize the buildings(Length, width and height) as required easily.  
we can also change the colors easily.

**Comment by gnansai** [comment]
If we need new designs on building, we can alter these shapes to get complete new design.
![image](https://user-images.githubusercontent.com/25223402/151647964-60acb530-1d41-40c5-ac75-33dc19605650.png)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/151649078-ced5c731-d300-40b0-9037-df6b50f94e63.png)
I have made 4 variations,

**Comment by kfarr** [comment]
great! these look good to me

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/models/arcade-style-buildings

https://github.com/gnansai/3dstreet-assets/tree/main/sets/arcade-style-buildings/gltf-exports

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/151650397-ee9ab707-6775-412a-a76a-eef80db224a6.png)
These old buildings does not have any details on back and side parts.
But arched buildings has details on back and side parts.
I can remove the details on back and side parts if needed.

**Comment by kfarr** [comment]
Let's keep it as you have it already, it looks better to have details all around

**Comment by kfarr** [comment]
The asset build portion of this ticket is complete, next step is to add support for 3dstreet viewer

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/257
made the first PR in the 3DStreet repository to support arcade style buildings. I think that instead of asphalt, tiles around these buildings would look better?

**Comment by kfarr** [comment]
@Algorush tiles like the sidewalk?

**Comment by kfarr** [comment]
ok done! https://github.com/3DStreet/3dstreet/pull/257

**Comment by kfarr** [comment]
![Image](https://user-images.githubusercontent.com/470477/231005156-014ce7b8-6238-4bfe-9dc6-a57b755c7ebe.png)

https://github.3dstreet.org/#https://streetmix.net/kfarr/82
