### ISSUE TITLE
Create a "Work from Home" banner texture

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#31]
The text should say "Work from Home"

Inspiration:
https://www.dreamstime.com/your-name-here-banner-exterior-vacant-building-lease-rent-i-your-name-here-banner-exterior-vacant-image157779906

This will be placed on a building

**Comment by gnansai** [comment]
![unknown](https://user-images.githubusercontent.com/25223402/181876959-85524efd-0933-494d-a582-113cef7152e0.png)

**Comment by kfarr** [comment]
@gnansai can you share this banner in whatever format is easiest - glb or png or other? I can't seem to find where this is located in this repo

**Comment by gnansai** [comment]
Hi @kfarr 
I added glb file here
https://github.com/gnansai/3dstreet-assets/tree/main/sets/wfh-banner/gltf-exports
