### ISSUE TITLE
Create low poly car m2 model

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#32]
https://www.carvana.com/vehicle/2442051

**Comment by JLansey** [comment]
The back of the car doesn't matter too much; but to make it look like a real BMW we need to capture the distinctive shape of the grills in front.
![image](https://user-images.githubusercontent.com/4146681/183321288-c31221a0-f726-484f-886c-7f2a128ecfb4.png)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/184948209-fd033aa9-7f90-4a24-8ccd-c1cc49e09825.png)
![image](https://user-images.githubusercontent.com/25223402/184948226-354741bc-5b78-46ab-9931-24d72bc61c28.png)
![image](https://user-images.githubusercontent.com/25223402/184948823-d5b1696e-c315-489b-b9f4-a36fdc4131fc.png)

**Comment by gnansai** [comment]
![unknown](https://user-images.githubusercontent.com/25223402/185154887-8c78f3e8-1e89-4b59-9c14-5e43faeb1138.png)
Added Logo

**Comment by JLansey** [comment]
Great! I think just transparent in the center though - to be true to the spirit of not actually copying their logo.
So - whatever color the car is - will be in the center.
Also - maybe try making the car this color: (though we can have some variants)
<img width="192" alt="image" src="https://user-images.githubusercontent.com/4146681/185168379-ea2083fc-0627-40ce-b2ed-2c326192f6a8.png">

**Comment by kfarr** [comment]
implemented in loud-bicycle-game
