### ISSUE TITLE
create high poly / high quality material version of loud bicycle mini

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#34]
intended use case will be for https://loudbicycle.com/ shopping cart website for use with this embeddable gltf viewer https://modelviewer.dev/

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets-source/tree/main/sets/loud_mini_horn_PBR/gltf-exports
I have uploaded the gltf-model here
