### ISSUE TITLE
add co2 scrubber object to loud bicycle game

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#39]
Co2 scrubber that can be mounted on the bike similar in spirit to loud bicycle horn

Example product for inspiration:
https://www.globalindustrial.com/p/global-industrial-8482-commercial-air-scrubber-3-stage-w-hepa-filtration-500-cfm-120v?infoParam.campaignId=T9F&gclid=Cj0KCQjw1bqZBhDXARIsANTjCPKi5ai4eNAs-5RSDudU7zBXcFzhSKzd7lWPyB-fOX7OZU-pYzNul-8aAuQiEALw_wcB

Picture
![Image](https://user-images.githubusercontent.com/470477/192127658-2510fcdf-57b5-46c5-84a2-272c5d76e10b.png)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/196351112-8c8414d4-9927-4f5b-9cbb-944b432a9892.png)
![image](https://user-images.githubusercontent.com/25223402/196351124-e78f42e1-4f89-462f-83e2-707afa543662.png)
![image](https://user-images.githubusercontent.com/25223402/196351143-c0aa79a6-760c-4d48-8a00-21030d6d5d72.png)
![image](https://user-images.githubusercontent.com/25223402/196351169-c16c2434-3b47-4937-8ced-6da7cb3f21fc.png)
Hi @kfarr 
Here is an update on the C02 Scrubber.
Please check when ever you are free and let me know if we need more details on the model.

**Comment by kfarr** [comment]
@gnansai looks good, this has been approved in discord by Jonathan. 

Next step is to add source files to `3dstreet-assets-source` as well as compress with gltfpack to `3dstreet-assets-dist` in the same manner as the other loud-bicycle-game assets. Let me know if you need more info

**Comment by gnansai** [comment]
@kfarr I added the c02-scrubber here
https://github.com/gnansai/3dstreet-assets-source/tree/main/sets/c02-scrubber/gltf-exports
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/c02-scrubber/gltf-exports/meshopt

**Comment by kfarr** [comment]
I have cherry picked this and merged the co2 scrubber into `3dstreet-assets-dist` repo here: 
https://github.com/3DStreet/3dstreet-assets-dist/blob/main/sets/c02-scrubber/gltf-exports/meshopt/co2-scrubber.glb

Next is to add to the loud-bicycle-game in this section:
https://github.com/3DStreet/loud-bicycle-game/blob/main/src/index.html#L262

**Comment by kfarr** [comment]
Added to loud bike game in this PR https://github.com/3DStreet/loud-bicycle-game/pull/61

![Image](https://github.com/3DStreet/3dstreet-assets-source/assets/470477/d126bb10-f298-4c65-b95d-adc22f863915)
