### ISSUE TITLE
create isuzu truck delivery model

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#41]
This will be replacing the existing box truck model:
https://github.com/3DStreet/3dstreet-assets-source/blob/main/sets/vehicles/individual-glb-files/box-truck.glb

You can modify or replace it completely. The goal is to have same general shape and dimensinos as isuzu box truck.

3d scan: https://poly.cam/capture/6F2A2222-095C-4921-9343-E8F6901E35EE
Spec sheet see page 10: https://www.isuzucv.com/en/app/site/pdf?file=2024N-SeriesDieselProductBrochure_Final.pdf
Link to truck info: https://en.wikipedia.org/wiki/Isuzu_Elf

**Comment by gnansai** [comment]
Hi @kfarr 
Is is possible to download this model?
https://poly.cam/capture/6F2A2222-095C-4921-9343-E8F6901E35EE

**Comment by kfarr** [comment]
Yes attached here:
[isuzu-truck-scan-poly.glb.zip](https://github.com/3DStreet/3dstreet-assets-source/files/10677667/isuzu-truck-scan-poly.glb.zip)

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update on the Isuzu truck. Let me know your suggestions.
The Geometry will be converted to triangles automatically.
![image](https://user-images.githubusercontent.com/25223402/220151542-5ef16bb4-7d56-4dce-b2a9-b02e7f104033.png)
![image](https://user-images.githubusercontent.com/25223402/220151663-f4114158-6092-4a28-a884-aa511357ba5f.png)
![image](https://user-images.githubusercontent.com/25223402/220151712-8afd6e86-2e96-460e-951c-bec3f0075124.png)
![image](https://user-images.githubusercontent.com/25223402/220151868-632d7474-0af4-4b87-8705-f5f0180eb2e7.png)

**Comment by kfarr** [comment]
@gnansai this is excellent! can you create a rigged dist version draco compressed in the dist repo just like you did for the prius? https://github.com/3DStreet/3dstreet-assets-dist/compare/main...gnansai:3dstreet-assets-dist:main

**Comment by gnansai** [comment]
I added Isuzu truck here

https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles-rig/gltf-exports/draco/isuzu-truck-rig.glb
