### ISSUE TITLE
create car model similar to toyota prius to replace sedan

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#42]
the [current sedan car model](https://github.com/3DStreet/3dstreet-assets-source/blob/main/sets/vehicles-rig/sedan-rig.glb) appears to be similar to the ford crown victoria used for taxis and police in the US. We can keep this as a backup, but it is an old car that is not seen as often.

Instead we should create a newer model based on the popular toyota prius sedan used for taxi and ride sharing services like Uber and Lyft in the US

example photogrammetry scan from sketchfab: https://sketchfab.com/3d-models/toyota-prius-2009331e9eae41a2bf9e52454b746c64

the vehicle should have the same rigged wheels as others

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update on the toyota prius model
![image](https://user-images.githubusercontent.com/25223402/217284019-25dcf097-3154-4393-8ccf-21b647afe1cb.png)
![image](https://user-images.githubusercontent.com/25223402/217284061-2b04eb33-fe90-4829-8310-81d61e002af4.png)
![image](https://user-images.githubusercontent.com/25223402/217284093-d9a8eed2-2115-444e-8813-925a4af4aeec.png)

**Comment by gnansai** [comment]
I have added the 3D files here
https://github.com/gnansai/3dstreet-assets-source/blob/main/models/vehicles/toyota_prius_car_v01.blend
https://github.com/gnansai/3dstreet-assets-dist/blob/main/objects/vehicles-rig/toyota-prius-car-rig.glb

**Comment by kfarr** [comment]
Wow @gnansai this is beautiful!!

**Comment by kfarr** [comment]
Can we run this through draco compression as well like the other assets? Or I can marge this first and we can do as a separate step if easier to let us handle.

**Comment by gnansai** [comment]
Hi @kfarr , I can add draco compression directly while exporting from Blender.
Donot mearge this fork yet, I had added meshopt compression in all assets. It might replace all the exisitng assets.

**Comment by kfarr** [comment]
Ok note the way that we have directory path /draco in the dist repo

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles-rig/gltf-exports/draco/toyota-prius-rig.glb
I added the model to the draco folder

**Comment by kfarr** [comment]
Next step:
- Ensure this is in the distro repo
- Change the default sedan object from the legacy sedan to the new sedan
- Ensure the existing sedan is still included in commented code. In the future this would be lazy loaded and called "sedan-crownvic"
