### ISSUE TITLE
new truck model should have single tires in front

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#46]
the front right and front left wheels should be only one wheel on each side, not double wheels on each side. (Only the back should have double wheels)

Remove the wheels x'ed out here:
![image](https://user-images.githubusercontent.com/470477/225204196-1635e6e5-42f3-40d6-bab3-da63619783ee.png)

**Comment by gnansai** [comment]
I removed one of the front tire of the new truck.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles-rig/gltf-exports/draco/isuzu-truck-rig.glb
![image](https://user-images.githubusercontent.com/25223402/225237691-1ff68a1d-ecee-49b6-a66a-c34a92e36b43.png)

**Comment by kfarr** [comment]
@gnansai thanks this looks great!
