### ISSUE TITLE
create new low poly bus

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#48]
goal:
- we want a New Flyer MD40 bus (like [flyer-bus](https://github.com/3DStreet/3dstreet-assets-source/blob/main/sets/flyer-bus/gltf-eports/flyer-bus.glb)) but with the style of low poly art in the same way that we have made other vehicles and objects
- it will replace both the flyer-bus as well as the [city-bus](https://github.com/3DStreet/3dstreet-assets-source/blob/main/sets/vehicles-rig/city-bus-rig.glb) model
- it should have a basic interior like city-bus

This new low poly new flyer bus will replace both as the only bus model in the app

**Comment by gnansai** [comment]
Hi @kfarr 
I started working on the Flyer bus
Do you need these text details?
![image](https://user-images.githubusercontent.com/25223402/230039358-a6fb6d8f-2dfb-49d6-9fef-184cb845ee34.png)

**Comment by kfarr** [comment]
@gnansai for now we don't need those details. we can add in decals and text later in the app as needed

**Comment by kfarr** [comment]
@gnansai also ideally we could use a different color scheme. That one is new york, it would be nice to match the san francisco color scheme. However we should not use the logo just the colors. Here are 2 good examples:
* https://www.turbosquid.com/3d-models/3d-san-francisco-trolleybus-sfmta-muni-short-1872478
* https://www.turbosquid.com/3d-models/3d-model-san-francisco-trolleybus-sfmta-muni-mid-poly-1872502

**Comment by gnansai** [comment]
Hi @kfarr 
I have made the flyer bus like this. Please check this when ever you can and let me know your suggestions.
![image](https://user-images.githubusercontent.com/25223402/233907486-2839c7b7-7c73-478c-bd7c-68f8b410321e.png)
![image](https://user-images.githubusercontent.com/25223402/233907505-4bea4cab-6a7f-4c98-8751-7b799ee24aa0.png)
![image](https://user-images.githubusercontent.com/25223402/233907515-ee90f66b-37ac-4ece-a71e-a87bcd59086e.png)
![image](https://user-images.githubusercontent.com/25223402/233907522-eee15989-8571-4d4f-9f89-3bb62f39ff70.png)

**Comment by kfarr** [comment]
Wow this is so good @gnansai ! I have a few edits below. I will try to add pictures too:
1. remove front reflector stickers
2. add side turn signals
3. change rear tail light clusters
4. add rear center high-mounted stop light
5. continue front windshield glass above destination sign (destination sign should be "inside" the front windshield glass
6. change position of right-side window destination to front-most passenger window
7. this is a "low floor" bus, ensure floor of bus is at the same as black line under the doors
8. double check - is there a left side destination sign?
9. add technical closet behind driver above front-left wheel well

**Comment by kfarr** [comment]
1. 
![image](https://user-images.githubusercontent.com/470477/234167474-06f9bb0a-f38c-4249-b14e-bf802f028b3b.png)

2, 5, 8, 9:
![image](https://user-images.githubusercontent.com/470477/234169190-ebe29efc-e475-45ed-83f9-08a8597f3a06.png)

3, 4, 10:
![image](https://user-images.githubusercontent.com/470477/234169773-a2be2863-a93d-48d5-ae4f-21e01e61929c.png)


7. See the floor via open door in this image: 
![image](https://user-images.githubusercontent.com/470477/234169277-da1fd9d9-a232-45bb-ae78-6361a2e08478.png)

**Comment by gnansai** [comment]
Hi @kfarr 
Thanks for the suggestions with reference images. I will work on it and update you.

**Comment by kfarr** [comment]
@gnansai confirming this is still in-progress, nothing new to review yet?

**Comment by gnansai** [comment]
Hi @kfarr 
Here is the latest version of the bus. Please check it when ever you can and let me know if you need any changes.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/flyer-bus/gltf-exports/draco/flyer-bus_v03.glb
![image](https://user-images.githubusercontent.com/25223402/235336767-8d11d409-36a5-450a-a503-e8c5338a24d7.png)
![image](https://user-images.githubusercontent.com/25223402/235336771-1ee24729-a3eb-414e-90ea-101bd146bbad.png)
![image](https://user-images.githubusercontent.com/25223402/235336777-40c9f52c-b38d-47df-b242-eea7391def5e.png)
![image](https://user-images.githubusercontent.com/25223402/235336785-51d6606b-022b-4c52-9295-9263276408e5.png)

**Comment by kfarr** [comment]
this is excellent. as a separate ticket we can make a low-floor version.

**Comment by kfarr** [comment]
Next to close this ticket:
* replace instances of the old flyer bus AND the old synty city bus with this new-flyer city bus
* fix legacy rotation for old new flyer bus
* remove the 2 old models
* only use this one going forward

**Comment by kfarr** [comment]
All good, last thing is for KF to remove old `city-bus` model(s) from repo(s)

**Comment by kfarr** [comment]
done!
