### ISSUE TITLE
new truck model should have centered roof top marker lights

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#49]
the 3 roof lights highlighted here should be centered. currently they are right of center 
![image](https://user-images.githubusercontent.com/470477/226533175-06fe52e1-d260-4482-ae19-f25f265c1e24.png)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/226606543-6f99b2c2-6291-4874-b173-a52b13daa176.png)
I updated the truck roof top lights

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet-assets-dist/pull/10/commits/d293ea9e779d12b6c4bcf398c0cf2f49ca9e464c
