### ISSUE TITLE
bicycle models to have an unlit red "led light" material

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#50]
this would be a second material on bicycles that have riders. the material can use the same texture atlas, the only difference is that it is unlit so it will appear "bright" in a darker night scene.

the red LED should be beneath the back-seat of the bike model

![image](https://user-images.githubusercontent.com/470477/228975525-5a09cb38-9556-4db2-b581-5b3f36c36560.png)

**Comment by gnansai** [comment]
Hi @kfarr 
I added red light at the back. Let me know your suggestions.

![image](https://user-images.githubusercontent.com/25223402/229286390-18755d4e-99be-4b3f-be82-710617e289b1.png)
![image](https://user-images.githubusercontent.com/25223402/229286400-74586275-585c-4342-a56b-6cd8e9c7f799.png)

**Comment by JLansey** [comment]
Hi - wow you did a good job matching my scribble!
But please only include the top piece not the bottom piece (unless I'm missing some reason why the light should be split in two?)
<img width="375" alt="image" src="https://user-images.githubusercontent.com/4146681/229501216-3e55d976-b2a6-425b-a8d1-19f273f57fbc.png">

Also if it is possible, can you make it blink at 1Hz between this bright red color, and dim red.

**Comment by gnansai** [comment]
Hi @JLansey 
The Overall animation is looping for every 28frames.
Even if I offset the blinking animation a little, the blinking will repeat at certain interval of time due to animation Looping.  
I think we need to do the light blinking with Three js or Aframe code if we need more control over it.

**Comment by JLansey** [comment]
Ohhhh that makes sense. It isn't important enough to spend time with 3js. How about make the blink at 2Hz with the dark phase when the light passes the center.
I think this will look nice and symmetrical.

**Comment by gnansai** [comment]
Hi @JLansey 
Please check this and Let me know and let me know your suggestions.

![ezgif-2-7d68edccc5](https://user-images.githubusercontent.com/25223402/233267767-99f49e04-1fc6-4df7-95c5-11f3378e4ef4.gif)

**Comment by gnansai** [comment]
Hi @JLansey 
I have uploaded the gltf files if you want to test them.
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco

**Comment by JLansey** [comment]
looks good, don't see the light on the kids bike.
also - would be great to have them all blink the same way as the first.

**Comment by gnansai** [comment]
Hi @JLansey 
I updated the kid bicycle animation with Light.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/cyclist-animation/gltf-exports/draco/Kid_cyclist_animation_v01.glb
![image](https://user-images.githubusercontent.com/25223402/233820998-4e5e0069-589c-4118-aa4d-312d4c702e11.png)

**Comment by kfarr** [comment]
confirmed these are present in the loud bike game now, however the default camera angle prevents light from being visible

![Image](https://github.com/3DStreet/3dstreet-assets-source/assets/470477/8be360f8-eb5f-4c5a-bd53-74327d7a625b)
