### ISSUE TITLE
character eyebrow edits

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#51]
The following edits are needed for character eyebrows:
- remove "unibrow", all characters should have separate eyebrows, not 1 combined eyebrow. For example:
![unknown-2](https://user-images.githubusercontent.com/470477/228976144-657f7574-04c0-4be2-b730-bde9b00047ef.png)

- all characters should be neutral or happy as indicated by eyebrows. This character looks angry and should be neutral or happy with eyebrows pointing slightly up instead of down: 
![unknown-9](https://user-images.githubusercontent.com/470477/228976035-488a32f7-a278-49d8-8848-f6a86a605454.png)

**Comment by kfarr** [comment]
thanks @gnansai they all look good to me. Can you also update the animated versions of these characters if needed?

**Comment by gnansai** [comment]
sure @kfarr

**Comment by gnansai** [comment]
Hi @kfarr 
I have uploaded the updated characters here
1. https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cargo-bike-animation/gltf-exports/draco
2. https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco
3. https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/human-characters-animation-seperated/gltf-exports/draco
4. https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/human-characters-poses-1/gltf-exports/draco
5. https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/human-characters-poses-2/gltf-exports/draco

**Comment by kfarr** [comment]
- assets merged
- next to verify in production
