### ISSUE TITLE
create new low poly light rail vehicle model

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#52]
target likeness is sfmta siemens LRV:
https://www.turbosquid.com/3d-models/3d-san-francisco-tramway-muni-sfmta-siemens-s200-1868439

(I can get IRL photos or scans if helpful)

basic low poly interior as well

this will replace existing https://github.com/3DStreet/3dstreet-assets-dist/blob/main/objects/tram_siemens_avenio.gltf

**Comment by gnansai** [comment]
Hi @kfarr 
I have uploaded the light rail vehicle here. I will clean up and Rig the model. I will few more details. 
Please check it when ever you can and let me know your suggestions.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/light-rail-vehicle/gltf-exports/draco/light-rail-vehicle-v01.glb
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/5aa7912d-62ad-49fd-a367-3241194b03e9)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/83bf309c-83e7-4839-a5ea-b0375420f8c5)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/1f33ef30-9723-4038-b5a7-f9a371150d7f)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/7d17303c-4b0b-4139-954d-444b36328fd5)

**Comment by gnansai** [comment]
Hi @kfarr
I added very basic interior and side indicators. 
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/2f1b67b2-053e-464a-aad8-5b2324d7d09c)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/95ae0bc9-502c-41d8-aeee-d9008cd0986a)

**Comment by kfarr** [comment]
Hi @gnansai the train looks beautiful, the only thing missing is the operator cab on the opposite side (instead of a flat back):
![Uploading image.png…]()

Each side should be the same. See in this example how there are driver cabs on both sides:
https://p.turbosquid.com/ts-thumb/8j/XHZC06/Z7/sanfranciscotramwaymunisfmtasiemenss2000000/jpg/1647412190/1920x1080/fit_q87/dba7b400222e1cbccd30e6130ec975dcc0679d21/sanfranciscotramwaymunisfmtasiemenss2000000.jpg

**Comment by gnansai** [comment]
Hi @kfarr 
I have added the latest version with changes here.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/light-rail-vehicle/gltf-exports/draco/light-rail-vehicle-v02.glb
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/3f4164be-d35d-4985-ad3c-5774034dc5d7)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/c1810249-9df2-4e59-90a7-a0be19bbee27)

**Comment by kfarr** [comment]
@gnansai this is perfect! are the source and dist repos ready for me to merge as-is?

**Comment by gnansai** [comment]
Hi @kfarr 
I have uploaded the latest files here.
Yes, You can merge as-is.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/light-rail-vehicle/gltf-exports/draco/light-rail-vehicle-v02.glb
https://github.com/gnansai/3dstreet-assets-source/blob/main/models/light-rail-vehicle/light_rail_vehicle_v02.blend

**Comment by kfarr** [comment]
Ok thanks I've merged these, next step to update assets.js

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/289
