### ISSUE TITLE
bake animation to geometry shape keys

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#54]
Goal:
- characters can be used animated or not animated and they will work for both
- file size is reduced as only 1 type of animation is used, no bones or dynamic animation capability

Ideally the first frame of a baked animation for each of our 16 characters would exactly match the current static character pose. In other words if we load the character without animation, it looks like the current static pose. If we animate it, it will have a loop that is prebaked without bones. Would that make the file size smaller for each?

> Its called Shape Keys in Blender and Morph Targets in Three js
> here are some examples of Morph targets
> https://threejs.org/examples/?q=morph#webgl_morphtargets_horse
> https://threejs.org/examples/?q=morph#webgl_morphtargets_face
> 
> I need to experiment If the file size reduces when we use baked Geomrty animation.
> 
> Kieran Farr Today 08:45 AM
> Would there be an alternative to not use bones and just bake the mesh animation to reduce file size as much as possible?
> 
> Could you open an issue on Github ? so that we can keep track on it.
> I can make two versions of walk animation with Bone animation and MorphTargets(Blender shape keys) animations.
> We can compare the file sizes.

**Comment by gnansai** [comment]
Hi @kfarr 
I made a test with baking the shape-keys to the geometry in Blender.
Here is the link to the test files
https://github.com/gnansai/3dstreet-assets-source/tree/main/models/human-characters/baking_test

**Comment by gnansai** [comment]
Here are my observations
1. The draco compression does not seems to reduce file size when using the shape keys.
![image](https://user-images.githubusercontent.com/25223402/233912692-28c17443-a44a-4921-91ff-c370634630d6.png)

2. If we use more shape keys the file size increases.
![image](https://user-images.githubusercontent.com/25223402/233913137-ca40da8a-fb0b-42dc-aaec-ae0fea21b854.png)

**Comment by kfarr** [comment]
Before tagging other people to help, restating this request in its entirety:
* in a-frame app we want to invoke 16 low poly characters via mixins
* the characters should be in a nice pose if not animated (not T hands out) or animated for walking in realtime or equivalent speed motion for other mobilities such as wheelchair loop. (animated or not is a user level setting)
* these will be loaded as separate glb files if required for the a-frame scene. most scenes do require all pedestrians
* there is not a need to assign other arbitrary animations to the 16 characters. they are either in a walking loop, or frozen
* we want to minimize the size of these assets to have a fast transport time.

What is best way to achieve the above requirements with the smallest file size?

PS. Should we also be optimizing for rendering? At the moment scenes with many animated pedestrians have low fps.
(example)

**Comment by kfarr** [comment]
thanks @gnansai for doing this research. I'm going to mark this ticket as closed / not doing. Instead we solved this with 2 other things:
* The conversion of everything to draco has helped with the filesize issue.
* The changes you just made as part of https://github.com/3DStreet/3dstreet-assets-source/issues/62 resolved the second issue here of having nice pose if not animated.

**Comment by kfarr** [comment]
thanks @gnansai for doing this research. I'm going to mark this ticket as closed / not doing. Instead we solved this with 2 other things:
* The conversion of everything to draco has helped with the filesize issue.
* The changes you just made as part of https://github.com/3DStreet/3dstreet-assets-source/issues/62 resolved the second issue here of having nice pose if not animated.
