### ISSUE TITLE
modify new low poly flyer bus to be low floor

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#55]
modify the new low poly new flyer xd40 bus to be low floor
the front of the bus until just behind the back door is all low floor with the exception of space for the wheel wells.

Here is a model example that does this correctly:
https://www.cgtrader.com/3d-models/vehicle/bus/new-flyer-xd40-xcelsior

This model is close but has an incorrect step near the front door that should not be there:
https://sketchfab.com/3d-models/mta-new-york-city-bus-27dfa90edf2849089a77734ab674b909

**Comment by kfarr** [comment]
Also the 2 turn signals on each side should be orange not red


![Image](https://user-images.githubusercontent.com/470477/235529814-6d48104d-e42c-46c8-b26d-77808d07b858.png)

**Comment by gnansai** [comment]
Hi @kfarr 
I have added the latest version of the bus here. Please check when ever you can and let me know if any fixes are needed.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/flyer-bus/gltf-exports/draco/flyer-bus_v04.glb

**Comment by kfarr** [comment]
@gnansai this is excellent!! Can I ask for 2 more final changes?
- For each of the wheel wells (where the frame meets the tiers) can we increase the number of polygons in these wheel wells? Right now there are about ~7ish segments on the half-circle of the wheel well and you quickly see the model is low poly, while the rest of the model looks really good. Maybe we could increase that to ~12-14 segments?
![image](https://user-images.githubusercontent.com/470477/235738373-38212a20-3efe-4347-bbd9-8d0d68e20b57.png)

- For each of the turn signals they area bit long, can we decrease the length to make it about 2/3rd of the current width?
![image](https://user-images.githubusercontent.com/470477/235738419-95e7d839-574b-4ef1-ace0-c5574c6767c3.png)

I promise that's the end of the edits!

**Comment by gnansai** [comment]
Hi @kfarr 
Thanks for the review,
I will work on it and update you.

**Comment by gnansai** [comment]
Hi @kfarr 
I made the fixes and uploaded the file here.
Please check it when ever you can and let me know if any fixes are needed.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/flyer-bus/gltf-exports/draco/flyer-bus_v05.glb
![image](https://user-images.githubusercontent.com/25223402/235856530-948f5593-e643-4fca-be79-bb08c1c05f22.png)
![image](https://user-images.githubusercontent.com/25223402/235856602-ad00c24a-48d5-45ce-9632-bc0d01544916.png)

**Comment by gnansai** [comment]
Hi @kfarr 
I have updated the wheel wells.
![image](https://user-images.githubusercontent.com/25223402/236100908-190f8298-f0e2-4c3f-bfc1-e7a1d3483d8f.png)
![image](https://user-images.githubusercontent.com/25223402/236100959-ddaac94b-060a-481f-af16-678c5baa78bd.png)
![image](https://user-images.githubusercontent.com/25223402/236100990-fcbcad3a-9eb9-4711-825f-b711f8014837.png)

**Comment by kfarr** [comment]
@gnansai excellent! seriously this is beautiful and less than 100kb for a model with interior! thanks for dealing with my weirdly specific feedback
