### ISSUE TITLE
non-animated character state should be natural pose, not T

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#62]
Characters and cyclists with animation should be in a natural position (not a T position) when animation is not activated.

Good
![image](https://github.com/3DStreet/3dstreet-assets-dist/assets/470477/f5ead7f4-d55d-4b0b-896e-d96cf835c256)

Bad
![image](https://github.com/3DStreet/3dstreet-assets-dist/assets/470477/f4e8a5fd-ae63-43f0-b97e-a0742b3ab689)

Here are files that are incorrect and need to be updated:
* all files in this directory: https://github.com/3DStreet/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco
* all files in this directory: https://github.com/3DStreet/3dstreet-assets-dist/tree/main/sets/human-characters-animation-seperated/gltf-exports/draco
* https://github.com/3DStreet/3dstreet-assets-dist/blob/main/sets/cargo-bike-animation/gltf-exports/draco/cargo_bike_animation_v1.glb

Here is an example of a character that is correct, however we are no longer using meshopt compression:
* https://github.com/3DStreet/3dstreet-assets-dist/blob/main/sets/cyclist-animation/gltf-exports/meshopt/cyclist-1-animation-v1.glb
* https://github.com/3DStreet/3dstreet-assets-dist/blob/main/sets/cyclist-animation/gltf-exports/meshopt/cyclist-2-animation-v1.glb
* https://github.com/3DStreet/3dstreet-assets-dist/blob/main/sets/cyclist-animation/gltf-exports/meshopt/cyclist-3-animation-v1.glb

How to test:
* download the file
* drag into this window: https://gltf-viewer.donmccurdy.com/ 
* and then uncheck animation from the dropdown ![image](https://github.com/3DStreet/3dstreet-assets-dist/assets/470477/051ae339-0a3a-4026-bea1-d5eba59f2fda)

**Comment by kfarr** [comment]
Update from @gnansai via chat:
> Thanks for providing detailed information. I will check those examples that you have shared.
> We can change the Rest pose in Blender, so when the Animation is not activated the rest pose is used.
> I will give a try with Cyclist and update you.

**Comment by gnansai** [comment]
Hi @kfarr 
We don't have to change the rest pose in Blender. Changing the rest pose breaks the animation. 
I just found out that keeping the "Use Current Frame" option checked would fix this issue.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/6b546cf1-3d57-45bb-907a-bb6ea235960c)

https://github.com/KhronosGroup/glTF-Blender-IO/issues/1802

I have updated these animations 
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cargo-bike-animation/gltf-exports/draco
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/human-characters-animation-seperated/gltf-exports/draco

Please check these when ever you can and let me know

**Comment by kfarr** [comment]
@gnansai yes this worked great!! I have confirmed all of these behave as expected now with this update

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet-assets-dist/pull/15
