### ISSUE TITLE
new low poly game asset request - 3d heart

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#63]
* 3d heart as red #e03939 color
* approximate dimensions -- roughly 1 meter high by 1 meter wide with 0.25 m depth
* use attached as example inspiration
[heart.glb.zip](https://github.com/3DStreet/3dstreet-assets-source/files/11876115/heart.glb.zip)

Will be used in-game for loud bicycle game

**Comment by JLansey** [comment]
FYI: Here is where I found the heart https://free3d.com/3d-model/heart-v1--539992.html
It includes .obj and .stl formats (I had to convert it to glb)

**Comment by gnansai** [comment]
Hi @kfarr @JLansey 
I have added the low poly heart model here.
glb file
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/heart-model/heart-model_v01.glb
source file
https://github.com/gnansai/3dstreet-assets-source/tree/main/models/3d-heart
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/22871b43-3b0e-4319-9aad-c3bd7b13a8d1)

**Comment by kfarr** [comment]
looks great @gnansai , merged and added to game!
