### ISSUE TITLE
[blocked need jlansey feedback] update bar building lighting

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#65]
in fog and dark skies the bar building lighting does not appear correctly in the loud bicycle game

Here is previous discussion on the topic:
https://github.com/3DStreet/3dstreet/issues/178

Instead, we would like to adjust the hue and/or saturation values of the bar exterior (green) and the windows.

@jlansey can you provide more specific feedback about what you'd like changed?

**Comment by gnansai** [comment]
Hi @kfarr
Could you share any screenshot of the building in the night foggy scene?

**Comment by kfarr** [comment]
here's one example 
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/470477/762186eb-bb09-4672-b0c7-09f9baaba45e)

**Comment by JLansey** [comment]
Also - one more thing about this - the Loud Logo on the top of the bar is hard to see because it is perpendicular to the building. maybe hang it off an an angle or something so it is possible to view it a little.
<img width="305" alt="image" src="https://github.com/3DStreet/3dstreet-assets-source/assets/4146681/0bd0b12c-6a0a-429d-a285-0fd86ab79818">

**Comment by gnansai** [comment]
Hi @JLansey 
I have rotated the Load logo
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/bc0a2811-3475-4715-803e-0532c2cdd869)

**Comment by kfarr** [comment]
@gnansai yes the rotated sign location is good. We'll wait to hear from @JLansey what color changes he specifies

**Comment by kfarr** [comment]
@JLansey can you provide an example of the colors you want? even a photoshop copy that you fill in desired colors

**Comment by gnansai** [comment]
Hi @kfarr @JLansey
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/irish-bar-building/gltf-exports/draco
I changed the window colors to gray 
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/4df5686a-9d9b-422b-82b8-6c576d45abec)

**Comment by kfarr** [comment]
looks good to me, i'll merge and we can close this
