### ISSUE TITLE
On bike model, get red blinking bike light to be in a visible place

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#66]
goal: on dark maps to have blinking light of bike clearly visible in camera to reflect proper cyclist practices in-game

issue: current placement is not visible from elevated camera perspective

here is current picture from game showing red light not visible:
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/470477/a968688d-405d-4bc9-a570-ab4eec6ca069)

here is a screenshot from a model viewer showing the camera angle required to see red light is much lower than the game camera angle
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/470477/13889a60-bc70-4aa9-b5ca-6c74c276ce42)

instead, place red dot lower than its current position. it may need to float in between the two tubes supporting the rear wheel, or it can be attached to the left-hand tube only

cc @jlansey

**Comment by JLansey** [comment]
Also probably better even if it would stick further out the back, like - under the seat but in back so its not blocked by the seat. If you move it lower it might look physically too close to the wheel.
<img width="357" alt="image" src="https://github.com/3DStreet/3dstreet-assets-source/assets/4146681/2b369742-7a54-4d12-9c53-857c1bc3b4c5">

**Comment by gnansai** [comment]
Hi @kfarr @JLansey I have moved the red light to the seat back.
Please check it and let me know your suggestions. 
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/44cc0b0c-7eef-49d1-a2f9-ece9d844a654)
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco

**Comment by JLansey** [comment]
The location is great, can we also make it wider/larger so it is more visible?

**Comment by gnansai** [comment]
Hi @JLansey 
I have made the light little bigger, Let me know your suggestions.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/64bedcaa-ae79-4d97-8e26-30adf3893631)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/7fa64ad0-3b8b-4fbc-8123-b8fa2395f066)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/9ff26a2f-6b3b-493f-91f8-dedd0d534ba7)

**Comment by gnansai** [comment]
Hi @kfarr 
I have added latest versions with bigger red light here.
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco

**Comment by kfarr** [comment]
Hi @gnansai we got this working in the game and it is good enough, however there is an odd z-fighting thing going on with the light that we're not sure how to fix. You can see in this video how the light "shimmers"

https://github.com/3DStreet/3dstreet-assets-source/assets/470477/ca46fa2c-4f89-45d9-9b6b-b30a5f81d8aa

**Comment by gnansai** [comment]
Hi @kfarr 
I have used two geometries for red light blinking. The red bright light geometry moves forward and backward overlapping the red non bright geometry for light blinking effect. The geometries are located very close to each other and overlap during animation, hence the issue of z-fighting is occurring.

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/a7464637-c863-4bae-8443-1e62132ec6c9)

**Comment by gnansai** [comment]
Hi @kfarr 
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/bfe81a51-fc72-42de-8c50-be1e81d54a25)

**Comment by gnansai** [comment]
Hi @kfarr 
I have tried to increase the distance between the light geometries to avoid z-fighting. Please test it and let me know.
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/bfe81a51-fc72-42de-8c50-be1e81d54a25)

**Comment by kfarr** [comment]
looks good to me, i'll merge and we can close this

**Comment by JLansey** [comment]
oh that is actually quite a clever solution @gnansai ! Thank you - and thanks for fixing the z-fighting issue.
