### ISSUE TITLE
change bicycle people

### ISSUE THREAD

**Issue by JLansey** [3DStreet/3dstreet-assets-source#67]
maybe the dutch bike? I don't think we have any animated ones with that.

**Comment by gnansai** [comment]
Hi @JLansey We have 3 options for the Bike
1. Modern Bike
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/d4f30972-ede2-4d9c-ae8e-e4bc2566e7bf)
2. Dutch Bike
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/3dae76bb-c3d2-4f1f-a48f-334b87d12a60)
3. Cargo Bike
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/bbff6139-a3ef-451e-82e2-94ea063c7eff)

**Comment by gnansai** [comment]
@JLansey 
We have these characters as options.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/2a1c8ce6-7d5d-45d5-be82-489c7f789643)

**Comment by gnansai** [comment]
Please let me know your suggestion on the bike and the character.

**Comment by JLansey** [comment]
How about 1 and 2 both on the dutch bike

**Comment by kfarr** [comment]
To be clear we are talking about adding 2 new cyclist files such as:
cyclist-4-animation-v1.glb
cyclist-5-animation-v1.glb

In cyclist 4 animation it should use this character on the dutch bike:
* ![image](https://github.com/3DStreet/3dstreet-assets-source/assets/470477/5297e278-7ebe-4435-a11f-0d46871d07d2)

Cyclist 5 animation it should use this character on a dutch bike:
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/470477/aa498972-11db-46d6-b894-5ffa3155da61)

**Comment by gnansai** [comment]
Hi @kfarr
I have animated this character with Dutch bicycle (cyclist-5-animation-v1.glb)
I have added glb file here. Please check it and let me know if any fixes are needed.
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/29786f0a-a892-47a8-a882-be5b6e3bd11f)

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/35537329-7703-4261-823d-d51caaffeaeb)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/de7986bf-0869-4e60-b3b6-dc6967c303dc)

**Comment by gnansai** [comment]
Hi @kfarr 
I was working on cyclist 4 who is wearing a mini dress.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/47373c1e-c75b-4a1d-ab81-3f55b8851187)
I looks fine from the back but There are overlapping geometries issue due to the mini dress.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/6db5e147-a7a3-4853-8b98-05dd01e46b49)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/4feff3a0-7d85-4c65-afed-223172c41f73)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/8303885c-bd88-4830-8bc7-52e0816efa4c)

**Comment by gnansai** [comment]
@kfarr 
Shall I use this character as cycles 4 ? It would not have overlapping issues. 
I can also change skin tone material for any other characters if needed.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/50debd85-a70a-4d8a-b924-4eb3b333af1a)

**Comment by gnansai** [comment]
Hi @kfarr 
I have updated cyclist 4 and cyclist 5
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/cyclist-animation/gltf-exports/draco

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/f1fc40ff-b860-4097-bce0-780a71d5aa6b)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/4c0e1bf2-4643-4024-bb59-eef46fff0aec)

**Comment by kfarr** [comment]
looks good to me, i'll merge and we can close this
