### ISSUE TITLE
export glb file with just the parklet

### ISSUE THREAD

**Issue by JLansey** [3DStreet/3dstreet-assets-source#68]
found inside the street-props object.

If you have time - the parklet has leaves coming through one of the seats - not sure if that is on purpose, or we could convert it to a normal bench, and push the leaves more to the side. not super important though.

**Comment by gnansai** [comment]
Hi @JLansey 
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/ab1f66c6-9412-4488-ae5f-66cd10180309)
I have removed the plants and added seats there.

**Comment by gnansai** [comment]
I noticed that, The transformations of the parklet were not applied. I am not sure if this causes the white parklet issue.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/bd343104-0616-4301-8266-7e5c6e64c3cd)

**Comment by gnansai** [comment]
I have applied the transformation to the parklet. I have updated the street-props file.
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/street-props/gltf-exports/draco
I have exported parklet as separate file
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/street-props-parklet/gltf-exports/draco

**Comment by gnansai** [comment]
Hi @kfarr @JLansey 
I used gltf-pipeline for draco compression, which reduced the file size more than the gltf-transform.
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/street-props-parklet/gltf-exports/draco
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/street-props/gltf-exports/draco

**Comment by kfarr** [comment]
Looks great!
