### ISSUE TITLE
self driving cruise car model

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#72]
In order to support the streetmix lane type self driving car we need a low poly cruise car

- basic interior similar to bus or tram style
- rigged wheels like others
- no logo image files, just the orange color scheme via palette

inspiration
https://www.turbosquid.com/3d-models/gm-cruise-automation-bolt-3d-model-1426275

**Comment by gnansai** [comment]
Hi @kfarr 
I have made progress on self driving car
I have uploaded the model here. I have not rigged the wheels yet. Please check it and let me know your suggestions.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles/gltf-exports/draco/self_driving_cruise_car.glb
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/3dd44aed-cc60-471e-88e6-a16cf3c39297)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/6d543e22-109b-4304-bdb8-129b7ba53805)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/084e4bed-5e51-4e0d-b9f3-4e57bf8fb40d)

**Comment by kfarr** [comment]
@gnansai this is excellent! I think this can be rigged now as-is, no changes needed from me

**Comment by gnansai** [comment]
Hi @kfarr 
I have updated the rigged "self driving cruise car".
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles-rig/gltf-exports/draco/self-driving-cruise-car-rig.glb

**Comment by kfarr** [comment]
@gnansai great, thanks!

next steps:
- [ ] merge with 3dstreet dist
- [ ] add support for streetmix driving lane autonomous vehicle variant

**Comment by kfarr** [comment]
@Algorush can I assign this to you for adding support to the autonomous vehicle driving segment of streetmix?

**Comment by Algorush** [comment]
> @Algorush can I assign this to you for adding support to the autonomous vehicle driving segment of streetmix?
Yes, of course.

**Comment by Algorush** [comment]
I can also add support for taxi segments

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/392

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/392
