### ISSUE TITLE
create fire ladder truck

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#73]
https://poly.cam/capture/90670D33-708B-4081-8188-1CE0B498C95B

same style as the previous engine truck

**Comment by gnansai** [comment]
Hi @kfarr 
Could you share the scanned model file ?

**Comment by kfarr** [comment]
sure here it is @gnansai 
[poly (1).glb.zip](https://github.com/3DStreet/3dstreet-assets-source/files/12826508/poly.1.glb.zip)

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update on the fire ladder truck. Please check it when ever you can and let me know your suggestions.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/57577a7d-0bee-4e76-acc3-32be515ea3d1)

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/0b28f822-3249-4caa-b900-b28d67b2f4aa)

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/03a6d376-c6b4-4d5b-b4d0-939b32e79509)

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/20c30391-198b-447a-9eb4-d42e5469b325)

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/ca684f06-29d0-4d61-93f2-2426e53017d1)

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/ca684f06-29d0-4d61-93f2-2426e53017d1)

**Comment by gnansai** [comment]
Hi @kfarr 
I have added the model here
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles/gltf-exports/draco/fire_truck_ladder.glb

**Comment by kfarr** [comment]
@gnansai thanks for all of this work! The ladder truck has finally shipped to production!
https://twitter.com/3dstreetapp/status/1740430994031984680
