### ISSUE TITLE
cucumber carl rigging

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#74]
For experimental purposes only, this was an experiment to rig an existing 3D model asset purchased from sketchfab.com.

WIP to rig from @gnansai pasted here as a zip file

[pickle_face_rig_test_01_bone_rig.glb.zip](https://github.com/3DStreet/3dstreet-assets-source/files/13302301/pickle_face_rig_test_01_bone_rig.glb.zip)

Videos showing rigging in use:
https://github.com/3DStreet/3dstreet-assets-source/assets/470477/e6833d0c-a461-4737-a307-8ece2a60b5ef
https://github.com/3DStreet/3dstreet-assets-source/assets/470477/20aca413-0d90-45fe-9540-ca6b34533c5e

**Comment by kfarr** [comment]
Potential modifications:
- new name: Cucumber Carl
- new shape: cucumber -- instead of warts have vertical cucumber lines
- mustache and belly

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update of cucumber carl
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/
Here are the files
[CucumberCarl_Rig.zip](https://github.com/3DStreet/3dstreet-assets-source/files/13614564/CucumberCarl_Rig.zip)
25223402/5f866035-27b6-4000-ae28-400c3dee4ba3)

**Comment by kfarr** [comment]
@gnansai does this have an animation or just rigging?

could you add an animation of length 1 second that goes from fully closed to fully open mouth?

**Comment by gnansai** [comment]
Hi @kfarr 
I have added the animation of mouth closed - open - closed
Here are the files
[CucumberCarl_Rig_v02_animation.zip](https://github.com/3DStreet/3dstreet-assets-source/files/13623796/CucumberCarl_Rig_v02_animation.zip)

Here is the screen record of the animation

https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/99c9bb46-4cc9-484e-8428-9a196051c1b8

**Comment by kfarr** [comment]
Excellent, thanks @gnansai ! I did a first pass at it and have some feedback from "user testing" with my kids:
- can we 5x the mouth opening distance on the 1 second animation? In other words, if we say the height at 1 second is 1cm, instead we would like a 5cm maximum mouth opening height. This may require deforming the cucumber mesh a bit to accommodate that mouth height. The reason is that people are moving their fingers wide and expect the cucumber to keep opening and don't understand why it stops at a specific location. I think 5 cm is reasonable extreme, 10cm is larger than the whole cucumber and starts to get really ridiculous.
- can you create a 2nd version named "Carla" that is a darker shade of green, no bumps, and has long hair perhaps dread-style with darker green than her skin? We will then make the option for the user to switch between carl and carla objects before entering AR mode

**Comment by gnansai** [comment]
Hi @kfarr
 II have increased the mouth opening distance(lower jaw) in the animation.
Here is the GLB file for the Cucumber Carl. Please test with this file and Do let me know if you face any issues.
[cucumber_carl_face_rig_test_03_bone_rig_animation.zip](https://github.com/3DStreet/3dstreet-assets-source/files/13657736/cucumber_carl_face_rig_test_03_bone_rig_animation.zip)

https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/34aefa88-b21b-47fc-84a2-ade5896166ee

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update of cucumber carla
[cucumber_carla_face_rig_test_01_bone_rig_animation.zip](https://github.com/3DStreet/3dstreet-assets-source/files/13659009/cucumber_carla_face_rig_test_01_bone_rig_animation.zip)

https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/55fbfe4c-4968-4940-a9be-11e2b65263e2

**Comment by kfarr** [comment]
@gnansai wow these look great, thanks!

**Comment by kfarr** [comment]
This task is complete from a modeling standpoint. This issue will be the "source of truth" for the models for now, it will be integrated as part of this ticket:
https://github.com/kfarr/cucumber-comedy-club/issues/1
