### ISSUE TITLE
san francisco cable car

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#78]
this will replace the godarvilletram.gltf model

it should be modeled after the San Francisco cable car, similar but much lower poly than this example model:
https://sketchfab.com/3d-models/san-francisco-cable-car-railway-videogame-asset-1e0c94a96a03434fb3b09b2c1cde4643

Target output is similar level of detail as the bus and LRV models that you did.

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update of San Francisco Cable Car
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/fef0e64d-874e-4248-a72b-952a4e727dbd)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/41a255c7-0eaa-44cd-b956-28f7774198cb)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/8e08623b-04fa-4ddb-8e28-85db4e4ac031)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/1d00b03c-299d-4bde-8260-41c10c453d5a)

**Comment by kfarr** [comment]
@gnansai this looks great. I don't think we need text right now, we can add later. The only remaining point is that the wheels fit a gauge of [3 ft 6 in (1,067 mm)](https://en.wikipedia.org/wiki/San_Francisco_cable_car_system)

**Comment by gnansai** [comment]
@kfarr Yes
It should fit the 3ft 6in guage.
I have maintained 3.5ft or 3ft 6in gap in between the wheels.
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/19914f1d-425f-472b-8d6c-af15538f7626)

**Comment by gnansai** [comment]
@kfarr 
I have added the san fracisco cable car model here 
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/sanfrancisco-cablecar/gltf-exports/draco

**Comment by kfarr** [comment]
merged
