### ISSUE TITLE
trash truck

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#82]
https://lumalabs.ai/capture/bc327712-9eda-4d80-b1ea-744295d85203

**Comment by kfarr** [comment]
Traditional garbage truck (rear loading instead of side-loading like the luma model) might be nice to have both options:
https://sketchfab.com/3d-models/garbage-truck-abc7705b46bd4e9fa7a245ea15f9d89a

**Comment by gnansai** [comment]
Hi @kfarr 
I looked at this gaussian splat 
https://lumalabs.ai/capture/bc327712-9eda-4d80-b1ea-744295d85203 
There seems to be not way to measure the dimensions. I could not find dimensions of this truck online.
Could you share if you have any info regarding the dimensions of this truck?
In future if we are planning to make any real world model like trash truck, I would prefer photogrammetry instead of gaussian splat as I can import photogrammetry model into the blender.

**Comment by kfarr** [comment]
Hi @gnansai sorry about that. Attached is a gltf export in mesh 
[Trash_truck_textured_mesh_lowpoly_glb.glb.zip](https://github.com/3DStreet/3dstreet-assets-source/files/14618247/Trash_truck_textured_mesh_lowpoly_glb.glb.zip)

I don't think that mesh will have the correct scale, however.

Here is another suggestion. There is a license plate on the front and back (37971H1). California license plates are [12" by 6" (30cm x 15cm)](https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_California)

We can infer the scale size of the rest of the model using that as a guide.

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update of trash-truck-side-loading.
I have uploaded the model here.
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles/gltf-exports/draco/trash-truck-side-loading.glb

I have separated the wheels and named them like this.
F-front wheels
B-back wheels
L- left
R- right

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/7fb815bf-f951-46a5-8626-3ca8d7a05d65)


![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/3083dbf0-1f69-469a-b2e9-a5b6d5a593ba)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/76c01e2d-1e28-420a-8e76-6bc699820749)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/e6508b80-5ccd-4fe0-b060-f65d07fadb09)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/0a7f696a-0880-4b02-858b-ad63766f2562)

**Comment by gnansai** [comment]
Hi @kfarr 
Could you share any real world reference image to this "Traditional garbage truck" ?

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/559
