### ISSUE TITLE
convert 6 street safety models from U of O team

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets-source#84]
[new-objects-from-luke.zip](https://github.com/3DStreet/3dstreet-assets-source/files/14530869/new-objects-from-luke.zip)

creator attribution: Copyright 2024, Luke Walker, University of Oregon, Sustainable Cities Institute (SCI)
usage license: Creative Commons https://creativecommons.org/licenses/by-sa/4.0/

existing filename (from zip) and proposed short-name for converted asset:
bikecurbend.fbx "curb-island-end-rounded"
RRFBsign.fbx "sign-warning-ped-rrfb"
Bollard_Single.fbx "traffic-post-k71"
RaisedCrosswalk.fbx - "crosswalk-raised"
RoundIslandextended.fbx - "curb-traffic-island"
Speedhump.fbx - "speed-hump"

conversion tasks:
- convert to blender source file using same material methods as other 3dstreet objects
- export to separate glb files for use in application

**Comment by gnansai** [comment]
Hi @kfarr 
I have updated new object from Luke. I have added 3d street atlas material.
I have uploaded glb files here.
https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/new-objects-from-luke/gltf-exports/draco
I have added yellow color in the atlas texture for "sign-warning-ped-rrfb.glb".

![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/aa0cc34b-1a85-4ac7-b526-f8522ccb27fc)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/48a55e27-eff9-4b98-bfe4-080781257016)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/d57c552d-668d-41dd-b037-2ceba55450ce)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/045a2a22-35dc-4334-b26b-c63135400589)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/e0934cb1-af65-43d7-a807-523b885b2077)
![image](https://github.com/3DStreet/3dstreet-assets-source/assets/25223402/3d317553-a966-44f6-b214-bfabb3c87af3)

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/559
